#+TITLE: qbank — módulo de generación de preguntas (parte quiz)
#+AUTHOR: Andrés Bujosa, Marcos Bujosa
#+LANGUAGE: es
#+OPTIONS: toc:t num:t H:4
#+STARTUP: overview

# ─── Configuración de org-babel ───────────────────────────────────
#+PROPERTY: header-args:python :noweb yes
#+PROPERTY: header-args:jupyter-python :kernel qbank

# ─── LaTeX export ────────────────────────────────────────────────
#+LATEX_CLASS: report
#+LATEX_CLASS_OPTIONS: [10pt,a4paper]


#+LATEX_HEADER: \usepackage{fontspec}          % para fuentes Unicode
#+LATEX_HEADER: \usepackage{lmodern}           % o mejor, define una fuente explícita
#+LATEX_HEADER: \setmainfont{Latin Modern Roman} % o cualquier otra que quieras
#+LATEX_HEADER: \usepackage[spanish]{babel}

#+LATEX_HEADER: \usepackage{etoolbox}
#+LATEX_HEADER: \AtBeginEnvironment{verbatim}{\footnotesize}

# ─── Copyright ──────────────────────────────────────────────────────────────
# Copyright (C) 2020-2026  Andrés Bujosa, Marcos Bujosa
#
# This file is part of calcprop-qbank.
#
# calcprop-qbank is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# calcprop-qbank is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# ─── TeXinfo export ────────────────────────────────────────────────
# +TEXINFO_FILENAME: CalcPropQuiz.texi
# +TEXINFO_DIR_CATEGORY: The Info directory category (defaults to Misc).
# +TEXINFO_DIR_NAME: The short name used in the main Info directory

**** Ajustes para la compilación de la documentación               :noexport:
  :PROPERTIES:
  :UNNUMBERED: notoc
  :END:

# Para que no ejecute todo el código al exportar a pdf
#+PROPERTY: header-args :eval never-export
#+CALL: NombreEnChunksDeCodigo()


#+NAME: NombreEnChunksDeCodigo
#+BEGIN_SRC emacs-lisp :results silent
(setq org-babel-exp-code-template
         (concat "\n#+ATTR_LATEX: :options label=%name\n"
              org-babel-exp-code-template)
               )
(setq fill-column 100)
#+END_SRC


* Creación de preguntas de opción múltiple

*** Estructura del módulo =qbank._quiz=
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

El módulo completo está compuesto varios fragmentos de código se son descritos en los siguientes capítulos.
#+begin_src python :tangle src/qbank/_quiz.py :exports none
# Copyright (C) 2020-2026  Andrés Bujosa, Marcos Bujosa
#
# This file is part of calcprop-qbank.
#
# calcprop-qbank is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# calcprop-qbank is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#+end_src

#+NAME: qbank/_quiz.py
#+begin_src python :tangle src/qbank/_quiz.py :noweb no-export
from calcprop import *

<<Metodo auxiliar para juntar cuestiones en formato para profe>>
<<Definición de la clase Marcador>>
<<Definición de la clase Supuesto>>
<<Definición de la clase Cuestion>>
<<Definición de la clase ProblemaTipo>>
<<Definición de la clase ProblemaTipoProfe>>
<<Definición de la clase ProblemaVF>>
#+end_src

*** Uso del módulo
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

Para usar este módulo, primero se debe ejecutar
#+BEGIN_SRC jupyter-python :results silent
from qbank import *
#+END_SRC


** Clase =Marcador=

Usaremos la clase =Marcador= como una herramienta auxiliar para construir el árbol con todas las combinaciones posibles entre un conjunto de proposiciones y textos (que componen un conjunto de posibles enunciados), y un conjunto de cuestiones relacionadas con dichos enunciados. 

(/Posteriormente se descartarán de dicho árbol las combinaciones enunciado-cuestión en las que la veracidad o falsedad de la cuestión no se pueda deducir con las proposiciones declaradas en el enunciado./)

*** Funcionamiento General

Invocamos esta clase del siguiente modo: =Marcador(data)=, donde =data= es una lista de números enteros mayores que cero.
Por ejemplo, si invocamos  =Marcador([2, 3, 1])=, estamos pidiendo todas las listas =[i, j, k]= tales que $0 \le i < 2$,  $0 \le j < 3$  y $0 \le k < 1$ 
(es decir, la primera componente solo puede tomar dos valores (0 y 1), la segunda tres (0, 1 y 2) y la tercera solo puede valer $0$.

#+BEGIN_SRC jupyter-python
for i in Marcador([2,3,1]):
    print(i)
#+END_SRC

#+RESULTS:
: [0, 0, 0]
: [0, 1, 0]
: [0, 2, 0]
: [1, 0, 0]
: [1, 1, 0]
: [1, 2, 0]

*** Implementación

La clase =Marcador= es un [[https://docs.python.org/3/glossary.html#term-iterator][iterador]]. 
Para el argumento ~data=[n_1,...,n_k]~ genera todas las listas de la forma =[m_1,...,m_k]= tales que cada =m_i= es un número natural menor que =n_i=.

Esta clase =Marcador= está formada por los siguientes fragmentos de código:
#+NAME: Definición de la clase Marcador
#+begin_src python :noweb  no-export
class Marcador:
    <<Método __init__ para la clase Marcador>>
    <<Método __iter__ para la clase Marcador>>
    <<Método __next__ para la clase Marcador>>

#+end_src

- =__init__= :: El método =__init__= es el inicializador de instancias en Python y actúa como el constructor de la clase; su función principal es configurar el estado inicial de un objeto recién creado asignándole valores a sus atributos mediante el argumento =self=. Este método especial se ejecuta de forma automática y obligatoria cada vez que se instancia una clase, permitiendo que cada objeto nazca con datos propios y personalizados, lo que evita tener que definir las variables de manera manual tras la creación del objeto. Para profundizar en los detalles técnicos de su funcionamiento, la herencia y las buenas prácticas, puede consultar la sección sobre clases en la [[https://docs.python.org/3/tutorial/classes.html][Documentación Oficial de Python]].

Además, para construir un iterador necesitamos los métodos =__iter__= y =__next__=.

- =__iter__= :: El método especial =__iter__= es el encargado de hacer que un objeto sea iterable en Python, permitiendo que pueda ser utilizado directamente en bucles =for=, comprensiones de listas o cualquier contexto que requiera recorrer elementos uno a uno. Su papel preciso es devolver un objeto iterador (que puede ser el propio objeto =self= si este implementa el método =__next__=, o un objeto iterador dedicado de otra clase), estableciendo así el protocolo de iteración de Python. Al invocar este método, Python sabe exactamente cómo comenzar el recorrido de la estructura de datos, ya sea una colección nativa como una lista o una clase personalizada que hayas diseñado. Para comprender a fondo cómo implementar este método junto con el protocolo de iteración y los generadores, puede consultar la sección sobre iteradores en la [[https://www.google.com/search?q=https://docs.python.org/3/tutorial/classes.html%23iterators][Documentación Oficial de Python]].

- =__next__= :: El método especial =__next__= es la pieza fundamental que hace funcionar a un objeto *iterador* en Python, siendo el encargado de devolver el siguiente elemento disponible cada vez que se avanza en una secuencia. Este método es invocado automáticamente entre bastidores por la función nativa =next()= o al recorrer un bucle, y tiene la responsabilidad crucial de lanzar la excepción estándar =StopIteration= cuando se han agotado todos los elementos, lo que le indica a Python que la iteración ha terminado de forma segura. Junto con =__iter__=, conforma el protocolo de iteración completo de Python, permitiendo un control milimétrico sobre cómo se calculan y entregan los datos (incluso bajo demanda o de forma infinita). Para ver ejemplos prácticos de su implementación y entender cómo gestiona el flujo de datos, puede revisar la documentación sobre tipos iteradores en la [[https://docs.python.org/3/library/stdtypes.html#iterator-types][Referencia de la Biblioteca Estándar de Python]].

**** Método =__init__(self, data)=

Este método inicializa la clase y almacena en el atributo =self.data= el argumento =data=; que es una lista con los topes de cada una de las componentes de las listas que se van a crear. 
En el ejemplo anterior, =[2,3,1]=.

#+NAME: Método __init__ para la clase Marcador
#+begin_src python :noweb yes
def __init__(self, data):
    self.data = data
#+end_src

**** Método =__iter__(self)=

El método =__iter__= inicializa el estado del iterador. 
Este método genera la semilla del iterador.
Dicha semilla es una lista de ceros (con tantos ceros como elementos hay en =self.data=).
La lista =self.p= se entregará a =__next__= en la siguiente invocación al método. 


#+NAME: Método __iter__ para la clase Marcador
#+begin_src python :noweb yes
def __iter__(self):
    self.p = [0 for x in self.data]
    return self
#+end_src

**** Método =__next__=

Gestiona el avance del iterador. 
- =__next__= devuelve =self.p= en su estado actual (=n=), y coloca en =self.p= la lista siguiente usando la función auxiliar =Siguiente=.
- Si =self.p= es vacía detiene la iteración.

#+NAME: Método __next__ para la clase Marcador
#+begin_src python :noweb no-export
def __next__(self):
    <<Definición de la función local Siguiente>>
    if self.p == []:
        raise StopIteration
    n = self.p
    self.p = Siguiente(self.p, self.data)
    return n
#+end_src

***** Función auxiliar =Siguiente (x, y)=

Dentro del método =__next__= definimos de manera recursiva la función auxiliar local =Siguiente=, que es la función que calcula la lista siguiente.

La *función =Siguiente(x, y)=* es el corazón lógico de la clase. Utiliza *recursividad* para implementar un orden lexicográfico:

- =x=: lista de números naturales =[m_1...m_r]= tales que =m_i < n_i= (es la lista de la que queremos calcular la siguiente).
- =y=: lista de números naturales =[n_1...n_r]= mayores que cero (lista de topes).

La función =Siguiente= devuelve una lista =[k_1...k_r]=; que es la siguiente lista a =[m_1...m_r]= (según el orden lexicográfico) que aún cumple que =k_i < n_i=.
En caso de no existir tal lista devuelve =[]=.

****** Implementación:
- Intenta incrementar primero el último elemento de la lista (el de la derecha). 
- Si el elemento de la derecha alcanza su límite (~x[0]+1 == y[0]~), intenta incrementar el elemento anterior y "resetea" a cero todos los elementos a su derecha.
- Si todos los elementos han alcanzado su límite, devuelve una lista vacía =[]=, lo que señaliza el fin de la iteración.
#+NAME: Definición de la función local Siguiente
#+begin_src python :noweb yes
def Siguiente(x,y):
    if x == [] :
        return []
    s = Siguiente(x[1:],y[1:])
    if s == []:
        if x[0]+1 == y[0]:
            return []
        else:
            return [x[0]+1] + [0 for i in x[1:]]
    else:
        return [x[0]] + s
#+end_src

# Escribe una completa explicación del código de esta última subsección llamada ** Clase =Marcador=. Quiero que explique lo que hace y cómo lo hace, de manera que sirva de documentación añadida al código.


** Clases =Supuesto= y =Cuestion=
*** Clase =Supuesto(enunciado, semantica, precond)=

La clase =Supuesto= define la estructura para almacenar tres aspectos (atributos) del planteamiento de un problema mediante su constructor =__init__=.

- =enunciado= :: cadena de texto que presenta los supuestos en lenguaje humano.

- =semantica= :: proposición que traduce parcialmente el significado lógico del =enunciado= (contiene lo necesario para deducir las respuestas).

- =precond= :: es una proposición o bien cualquiera de los valores =True= o =False=.
  El objeto =Supuesto= será incluido en el problema solo si la evaluación de =precond= es =True=.

#+NAME: Definición de la clase Supuesto
#+begin_src python :noweb yes
class Supuesto:
    def __init__(self, enunciado, semantica, precond=True):
        self.e = enunciado
        self.s = semantica
        self.p = precond

    def __repr__(self):
        """Método de representación"""
        return 'Cuestión( Enunciado: ' + self.e + '; Semántica: ' + self.s + '; Precondición: ' + self.p + ')'
#+end_src

*** Clase =Cuestion(enunciado, semantica, precond)=

De manera análoga, la clase =Cuestion= define la estructura para almacenar cuatro aspectos (atributos) del planteamiento de un problema mediante su constructor =__init__=. 

- =enunciado= :: string que presenta la pregunta en lenguaje humano.

- =semantica= :: proposición =P= tal que =test(P, semantica_de_los_supuestos)= devuelve =True= si es imposible refutarlo a partir de las premisas, es decir, es imposible que =P= sea falso si las premisas son verdad.

- =precond= :: es una proposición o bien cualquiera de los valores =True= o =False=.
  El objeto =Cuestion= será incluido en el problema solo si la evaluación de =precond= es =True=.

- =exp= :: al exportar las preguntas al formato =xml= de Moodle, cabe la posibilidad de que Moodle ofrezca al alumno una explicación una vez ha contestado a las preguntas. En el atributo =exp= se especifica la cadena de texto con la explicación que debe mostrar Moodle.

#+NAME: Definición de la clase Cuestion
#+begin_src python :noweb yes
class Cuestion:
    def __init__(self, enunciado, semantica, precond=True, exp=""):
        self.e = enunciado
        self.s = semantica
        self.p = precond
        self.x = exp

    def __repr__(self):
        """Método de representación"""
        return 'Cuestión( Enunciado: ' + self.e + '; Semántica: ' + self.s + '; Precondición: ' + self.p + ')'
#+end_src

#+RESULTS: Definición de la clase Cuestion


** Clase =ProblemaTipo=

La clase =ProblemaTipo= permite, a partir de una lista de posibles enunciados y varias listas de posibles preguntas, generar muchas variantes de ejercicios de opción múltiple por simple combinatoria. 
Combina enunciados con una sublista de preguntas y, para cada pregunta calcula su veracidad o falsedad dados los supuestos del enunciado. 
Si no es posible decidir la veracidad o falsedad de una pregunta para un enunciado concreto, esa combinación enunciado-pregunta es descartada.

*** Implementación

La clase =ProblemaTipo= es un iterador que genera todas las versiones aceptables de un problema.
Cada variante resulta de tomar una de las opciones de cada una de las listas en =supuestos_y_cuestiones=. 
Si la precondición de alguna de las opciones elegidas es =False= (o resulta refutable), la variante entera del problema es rechazada y se evalúa la siguiente combinación disponible.

- El atributo =self.e= contiene la lista =supuestos_y_cuestiones=.
  El argumento =supuestos_y_cuestiones= es una lista de listas de strings, objetos =Supuesto= o objetos =Cuestion=.
  Cada lista representa un conjunto de opciones excluyentes.

  Por tanto, cada elemento de =supuestos_y_cuestiones= es a su vez una lista de opciones (excluyentes) correspondiente a cada componente (cada parte) del texto del problema.

  Por comodidad, en el caso de que una de esas listas consista en un único objeto (una única opción), también se permite escribir directamente dicho objeto sin encerrarlo en una lista; es decir, la lista =supuestos_y_cuestiones= también admite directamente objetos de tipo string, =Supuesto= o =Cuestion=.

  La combinación de distintas opciones crea el texto completo de una variante del problema.

#+NAME: Definición de la clase ProblemaTipo
#+begin_src python :noweb no-export
class ProblemaTipo:
    def __init__(self, supuestos_y_cuestiones):
        self.e = supuestos_y_cuestiones

    <<Método __iter__ para la clase ProblemaTipo>>
    <<Método __next__ para la clase ProblemaTipo>>
#+end_src

El método =__iter__= inicializa el iterador configurando las estructuras internas, mientras que el método =__next__= obtiene la siguiente variante válida del problema, asegurándose de desechar en el proceso aquellas cuyas precondiciones no se satisfagan.

**** Método =__iter__(self)=

El atributo =self.l= es la lista =self.e= normalizada para que todos sus objetos sean listas; =self.long= es el número de componentes que constituyen el texto de cada variante.
=self.i= es el iterador interno encargado de la combinatoria y =self.c= es un contador de intentos de generación.

#+NAME: Método __iter__ para la clase ProblemaTipo
#+begin_src python :noweb yes
def __iter__(self):
    self.l    = [x if isinstance(x,list) else [x] for x in self.e]
    self.long = len(self.l)
    self.i    = iter(Marcador([len(x) for x in self.l]))
    self.c    = 0
    return self
#+end_src

**** Método =__next__=

La generación de variantes de un =ProblemaTipo= se produce dentro de un bucle que solo se detiene cuando el intento de iterar el marcador interno, =next(self.i)=, lanza una excepción =StopIteration= por haberse agotado todas las combinaciones posibles.

En cada intento de generación:
1. El contador =self.c= se incrementa de forma consecutiva.
2. Las variables =enunciado=, =hipotesis= y =cuestiones= se inicializan vacías.
3. Se recorren uno a uno los componentes de la variante candidata.

Si todos los componentes superan con éxito sus respectivas validaciones, el método devuelve una tupla con el identificador del intento y las estructuras generadas: =(str(self.c), enunciado, cuestiones)=.

#+NAME: Método __next__ para la clase ProblemaTipo
#+begin_src python :noweb no-export
def __next__(self):
    self.c += 1
    while True:
        try:
            variante = next(self.i)
        except StopIteration:
            raise StopIteration

        enunciado    = ""
        hipotesis    = []
        cuestiones   = []

        for n in range(self.long+1):
            if n == self.long:
                return (str(self.c), enunciado, cuestiones)

            componente = self.l[n][variante[n]]
            <<Tratamiento en función del tipo de componente>>
#+end_src


El fragmento de código =<<Tratamiento en función del tipo de componente>>= procesa el =componente= que corresponda en cada iteración del bucle =for= según su tipo:

- Cuando el =componente= es una cadena, se considera parte del enunciado del problema y se concatena al string =enunciado=.
- Cuando el =componente= es un objeto =Supuesto=, se testea su precondición. Si =componente.p= es =True= o no es refutable a partir de las =hipotesis= acumuladas, su texto =componente.e= se añade al enunciado y su significado lógico =componente.s= se incorpora a las =hipotesis=. En caso contrario, el análisis de la combinación actual se interrumpe de inmediato mediante un =break=, se notifica en pantalla el descarte y se pasa a evaluar el siguiente elemento del marcador.
- Cuando el =componente= es un objeto =Cuestion=, se testea su precondición. Si es =True= o no es refutable a partir de las =hipotesis= acumuladas, el par (=componente.e=, veracidad o falsedad de =componente.s=) se añade a la lista de =cuestiones=. En caso contrario, se imprime la notificación en pantalla y se interrumpe el procesamiento de la variante mediante un =break=; esto hace que la combinación entera quede descartada de inmediato, ignorando cualquier componente o lista de cuestiones posterior que restase por evaluar en esa iteración.

#+NAME: Tratamiento en función del tipo de componente
#+begin_src python :noweb yes
if isinstance(componente, str):
    enunciado = enunciado + componente

elif isinstance(componente, Supuesto):
    if test(componente.p, hipotesis):
        enunciado = enunciado +  componente.e
        hipotesis = hipotesis + [componente.s]
    else:
        print('\n Supuesto: '   + str(componente.e) \
            + ' rechazado por ' + str(componente.p) + '\n')
        break

elif isinstance(componente, Cuestion):
    if test(componente.p, hipotesis):
        cuestiones = cuestiones + \
            [(componente.e,(True if test(componente.s, hipotesis) else False),1,componente.x)]
    else:
        cuestiones = cuestiones + \
            [(componente.e,'rechazada por ' + str(componente.p),0,componente.x)]
        print('\n Cuestion: '   + str(componente.e) \
            + ' rechazada por ' + str(componente.p) + '\n')
        break
#+end_src

*** Ejemplo de funcionamiento

Escribamos un hipotético ejercicio (es decir una lista que contiene cadenas de caracteres, supuestos, cuestiones, sublistas de supuestos o sublistas de cuestiones):

#+NAME: Ejemplo de programación de un ejercicio
#+BEGIN_SRC jupyter-python :results silent
ejercicio = [ "Considere ",
              [
                  Supuesto("A ", v("A")),
                  Supuesto("B ", v("B")),
              ],
              [
                  Supuesto("y que A implica C. ",    v("A") >> v("C")),
                  Supuesto("y que B equivale a D. ", v("B") ** v("D")),
              ],
              "Conteste: ",
              [
                  Cuestion("¿Se da C?", v("C"), exp="Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A"),
                  Cuestion("¿Se da D?", v("D")),
                  Cuestion("¿Se da E?", v("E"), v("D")),
              ],
              [
                  Cuestion("¿Se dan A y C?", v("A") & v("C")),
                  Cuestion("¿Se dan C y D?", v("C") & v("D")),
              ],
             ]
#+END_SRC

A continuación veamos lo que hace =ProblemaTipo= con la lista =ejercicio=. 
Observe que en cada iteración se toma un elemento de cada lista de supuestos y un elemento de cada lista de cuestiones para formar la combinación de un enunciado (compuesto por supuestos) y un subconjunto de preguntas (tantas como sublistas de cuestiones). Si alguna cuestión es descartada en una combinación, se salta a la siguiente combinación (indicando la cuestión descartada y el motivo). Así, =ProblemaTipo= muestra todas las combinaciones posibles de cuestiones que se pueden responder para cada combinación de supuestos. Fíjese que los elementos que no son listas (aquí las dos cadenas de caracteres) funcionan como sublistas con un único elemento (por eso en todas las iteraciones aparece tanto ='Considere'= como ='Conteste:'=).

#+NAME: Ejemplo de ProblemaTipo
#+BEGIN_SRC jupyter-python 
for i in ProblemaTipo( ejercicio ):
    print(i)
#+END_SRC

#+RESULTS: Ejemplo de ProblemaTipo
#+begin_example
('1', 'Considere A y que A implica C. Conteste: ', [('¿Se da C?', True, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se dan A y C?', True, 1, '')])
('2', 'Considere A y que A implica C. Conteste: ', [('¿Se da C?', True, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se dan C y D?', False, 1, '')])
('3', 'Considere A y que A implica C. Conteste: ', [('¿Se da D?', False, 1, ''), ('¿Se dan A y C?', True, 1, '')])
('4', 'Considere A y que A implica C. Conteste: ', [('¿Se da D?', False, 1, ''), ('¿Se dan C y D?', False, 1, '')])

 Cuestion: ¿Se da E? rechazada por v('D')


 Cuestion: ¿Se da E? rechazada por v('D')

('5', 'Considere A y que B equivale a D. Conteste: ', [('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se dan A y C?', False, 1, '')])
('6', 'Considere A y que B equivale a D. Conteste: ', [('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se dan C y D?', False, 1, '')])
('7', 'Considere A y que B equivale a D. Conteste: ', [('¿Se da D?', False, 1, ''), ('¿Se dan A y C?', False, 1, '')])
('8', 'Considere A y que B equivale a D. Conteste: ', [('¿Se da D?', False, 1, ''), ('¿Se dan C y D?', False, 1, '')])

 Cuestion: ¿Se da E? rechazada por v('D')


 Cuestion: ¿Se da E? rechazada por v('D')

('9', 'Considere B y que A implica C. Conteste: ', [('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se dan A y C?', False, 1, '')])
('10', 'Considere B y que A implica C. Conteste: ', [('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se dan C y D?', False, 1, '')])
('11', 'Considere B y que A implica C. Conteste: ', [('¿Se da D?', False, 1, ''), ('¿Se dan A y C?', False, 1, '')])
('12', 'Considere B y que A implica C. Conteste: ', [('¿Se da D?', False, 1, ''), ('¿Se dan C y D?', False, 1, '')])

 Cuestion: ¿Se da E? rechazada por v('D')


 Cuestion: ¿Se da E? rechazada por v('D')

('13', 'Considere B y que B equivale a D. Conteste: ', [('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se dan A y C?', False, 1, '')])
('14', 'Considere B y que B equivale a D. Conteste: ', [('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se dan C y D?', False, 1, '')])
('15', 'Considere B y que B equivale a D. Conteste: ', [('¿Se da D?', True, 1, ''), ('¿Se dan A y C?', False, 1, '')])
('16', 'Considere B y que B equivale a D. Conteste: ', [('¿Se da D?', True, 1, ''), ('¿Se dan C y D?', False, 1, '')])
('17', 'Considere B y que B equivale a D. Conteste: ', [('¿Se da E?', False, 1, ''), ('¿Se dan A y C?', False, 1, '')])
('18', 'Considere B y que B equivale a D. Conteste: ', [('¿Se da E?', False, 1, ''), ('¿Se dan C y D?', False, 1, '')])
#+end_example

Cuando la lista de cuestiones es extensa (o incluye aclaraciones), la representación en una tupla puede extenderse más allá de los márgenes de este documento al utilizar =print=. Para mejorar la claridad y facilitar la comprensión del funcionamiento de =ProblemaTipo=, desempaquetaremos los componentes devueltos por el iterador y los presentaremos de forma estructurada. Esto permitirá visualizar mejor los resultados.

En cada iteración, presentaremos el enunciado completo correspondiente, junto con las cuestiones incluidas, cada una en una línea separada (indicando su veracidad y la explicación incluida en el atributo el atributo =self.x= si no la hemos dejado vacía). Si la variante fue abortada, se indicará cuál fue la cuestión desencadenante y el motivo de la interrupción.

#+BEGIN_SRC jupyter-python
for i in ProblemaTipo( ejercicio ):
    # Desempaquetamos la tupla en variables
    id_pregunta, EnunciadoCompleto, lista_Cuestiones = i
    
    # Imprimimos los primeros datos
    print(f"ID: {id_pregunta}")
    print(f"Enunciado completo: {EnunciadoCompleto}")
    
    # Imprimimos la lista de c uestiones, cada cuestión en una línea
    print(*lista_Cuestiones, sep='\n')
    print('\n')
#+END_SRC

#+RESULTS:
#+begin_example
ID: 1
Enunciado completo: Considere A y que A implica C. Conteste: 
('¿Se da C?', True, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se dan A y C?', True, 1, '')


ID: 2
Enunciado completo: Considere A y que A implica C. Conteste: 
('¿Se da C?', True, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se dan C y D?', False, 1, '')


ID: 3
Enunciado completo: Considere A y que A implica C. Conteste: 
('¿Se da D?', False, 1, '')
('¿Se dan A y C?', True, 1, '')


ID: 4
Enunciado completo: Considere A y que A implica C. Conteste: 
('¿Se da D?', False, 1, '')
('¿Se dan C y D?', False, 1, '')



 Cuestion: ¿Se da E? rechazada por v('D')


 Cuestion: ¿Se da E? rechazada por v('D')

ID: 5
Enunciado completo: Considere A y que B equivale a D. Conteste: 
('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se dan A y C?', False, 1, '')


ID: 6
Enunciado completo: Considere A y que B equivale a D. Conteste: 
('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se dan C y D?', False, 1, '')


ID: 7
Enunciado completo: Considere A y que B equivale a D. Conteste: 
('¿Se da D?', False, 1, '')
('¿Se dan A y C?', False, 1, '')


ID: 8
Enunciado completo: Considere A y que B equivale a D. Conteste: 
('¿Se da D?', False, 1, '')
('¿Se dan C y D?', False, 1, '')



 Cuestion: ¿Se da E? rechazada por v('D')


 Cuestion: ¿Se da E? rechazada por v('D')

ID: 9
Enunciado completo: Considere B y que A implica C. Conteste: 
('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se dan A y C?', False, 1, '')


ID: 10
Enunciado completo: Considere B y que A implica C. Conteste: 
('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se dan C y D?', False, 1, '')


ID: 11
Enunciado completo: Considere B y que A implica C. Conteste: 
('¿Se da D?', False, 1, '')
('¿Se dan A y C?', False, 1, '')


ID: 12
Enunciado completo: Considere B y que A implica C. Conteste: 
('¿Se da D?', False, 1, '')
('¿Se dan C y D?', False, 1, '')



 Cuestion: ¿Se da E? rechazada por v('D')


 Cuestion: ¿Se da E? rechazada por v('D')

ID: 13
Enunciado completo: Considere B y que B equivale a D. Conteste: 
('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se dan A y C?', False, 1, '')


ID: 14
Enunciado completo: Considere B y que B equivale a D. Conteste: 
('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se dan C y D?', False, 1, '')


ID: 15
Enunciado completo: Considere B y que B equivale a D. Conteste: 
('¿Se da D?', True, 1, '')
('¿Se dan A y C?', False, 1, '')


ID: 16
Enunciado completo: Considere B y que B equivale a D. Conteste: 
('¿Se da D?', True, 1, '')
('¿Se dan C y D?', False, 1, '')


ID: 17
Enunciado completo: Considere B y que B equivale a D. Conteste: 
('¿Se da E?', False, 1, '')
('¿Se dan A y C?', False, 1, '')


ID: 18
Enunciado completo: Considere B y que B equivale a D. Conteste: 
('¿Se da E?', False, 1, '')
('¿Se dan C y D?', False, 1, '')
#+end_example


En el ejemplo anterior, se observa que, para cada combinación de supuestos, en cada iteración solo se presenta una cuestión de cada sublista de cuestiones. Dado que hay solo dos sublistas, esto resulta en la visualización de dos preguntas por iteración, esto dificulta la revisión y mantenimiento del banco de preguntas.

En el anterior ejemplo, y aunque existen únicamente cuatro enunciados posibles y cinco preguntas en total, la combinatoria ha generado 18 variantes no descartables, cada una con un subconjunto de solo dos preguntas. Esta complejidad complica la tarea de revisar y mantener un banco de ejercicios eficaz.


** Clase =ProblemaTipoProfe=

Para facilitar la revisión y el mantenimiento de cada ejercicio, es preferible poder ver, junto a cada enunciado, el conjunto completo de cuestiones. Esta es la finalidad de la clase =ProblemaTipoProfe=, que presenta todas las cuestiones para cada enunciado, indicando en cada caso si son =True= o =False= (o si serán descartadas). Para alcanzar este objetivo se utiliza el procedimiento auxiliar =CuestionesJuntas=, para creas una sublista para cada =Cuestion= que incluye únicamente dicha cuestión. De este modo, como al iterar se toma un elemento de cada una de las sublistas, se mostrarán todas las cuestiones a la vez.

*** Implementación

Tan solo hay dos diferencias en el código de la clase =ProblemaTipoProfe= respecto al código de la clase  =ProblemaTipo=. 
- La primera es que en =self.e= cada =Cuestion= aparece como único elemento de una sublista, para así lograr que se ven todas las cuestiones en cada iteración.
- La segunda diferencia se produce en la definición del método =__next__=, que aquí no oculta las cuestiones que sí son rechazadas cuando usamos =ProblemaTipo=.

#+NAME: Definición de la clase ProblemaTipoProfe
#+begin_src python :noweb no-export
class ProblemaTipoProfe:
    def __init__(self, supuestos_y_cuestiones):
        self.e = CuestionesJuntas(supuestos_y_cuestiones)

    <<Método __iter__ para la clase ProblemaTipo>>
    <<Método __next__ para la clase ProblemaTipoProfe>>
#+end_src


**** Método =__next__= para la clase =ProblemaTipoProfe=

Aquí la diferencia respecto del =<<Método __next__ para la clase ProblemaTipo>>= es el tratamiento de cada componente, pues aquí no se excluyen las preguntas que serán rechazadas en la versión para el estudiante. Aquí todas las cuestiones son incluidas, pero se da una indicación añadiendo ~'rechazada por'~ más la precondición que ocasiona el rechazo cuando se usa =ProblemaTipo=.
#+NAME: Método __next__ para la clase ProblemaTipoProfe
#+begin_src python :noweb  no-export
def __next__(self):
    self.c += 1
    while True:
        try:
            variante = next(self.i)
        except StopIteration:
            raise StopIteration

        enunciado     = ""
        hipotesis     = []
        cuestiones    = []

        for n in range(self.long+1):
            if n == self.long:
                return (str(self.c), enunciado, cuestiones)

            componente = self.l[n][variante[n]]
            <<Tratamiento en función del tipo de componente para la versión del Profe>>
#+end_src

**** Tratamiento en función del tipo de componente en la versión del Profe
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

#+NAME: Tratamiento en función del tipo de componente para la versión del Profe
#+begin_src python :noweb yes
if isinstance(componente, str):
    enunciado = enunciado + componente

elif isinstance(componente, Supuesto):
    if test(componente.p, hipotesis):
        enunciado = enunciado +  componente.e
        hipotesis = hipotesis + [componente.s]
    else:
        print('\n Supuesto: '   + str(componente.e) \
            + ' rechazado por ' + str(componente.p) + '\n')
        break

elif isinstance(componente, Cuestion):
    if test(componente.p, hipotesis):
        cuestiones = cuestiones + \
            [(componente.e,(True if test(componente.s, hipotesis) else False),1,componente.x)]
    else:
        cuestiones = cuestiones + \
            [(componente.e,'rechazada por ' + str(componente.p),0)]

#+end_src

**** Función auxiliar =CuestionesJuntas=

Este bloque de código define la función =CuestionesJuntas(lista)=, cuyo objetivo principal es *aislar cada objeto de la clase =Cuestion= dentro de su propia sublista individual*, manteniendo otros tipos de datos (como cadenas o listas de supuestos) intactos.

En detalle:
1. *=CreaLista(t)=*: Una función auxiliar que asegura que cualquier elemento sea tratado como una lista (si no lo es, lo envuelve en una para poder indexarlo).
2. *Iteración*: Recorre cada elemento =e= de la lista de entrada =lista=.
3. *Strings y No-Cuestiones*: Si el elemento es una cadena o si el primer elemento de su contenido (tras pasarlo por =CreaLista=) no es de tipo =Cuestion= (por ejemplo, un objeto de la clase =Supuesto=), se añade directamente a la lista resultante =p= mediante =append=.
4. *Aislamiento de =Cuestion=*: Si el elemento es una instancia de =Cuestion= o pertenece a una lista de cuestiones, se utiliza =extend(CreaLista(e))=, lo que descompone cualquier agrupación previa de =cuestiones=, añadiendo cada =Cuestion= como una sublista independiente (y con un único elemento) dentro de =p=.

*En resumen:* Transforma una lista mixta de modo que cada objeto =Cuestion= acabe confinado en una sublista propia. De este modo, el generador multidimensional las procesa de forma independiente y simultánea.

*Objetivo:* Esto permite que la clase [[Clase =ProblemaTipoProfe=][=ProblemaTipoProfe=]] muestre todas las cuestiones posibles para cada enunciado en lugar de una sola.

#+NAME: Metodo auxiliar para juntar cuestiones en formato para profe
#+begin_src python :noweb yes
def CuestionesJuntas(lista):
    def CreaLista(t):
        return t if isinstance(t, list) else [t]
    p = []
    for e in lista:
        if isinstance(e,str):
            p.append(e)
        elif not isinstance(CreaLista(e)[0],Cuestion):
            p.append(e)
        else:
            p.extend(CreaLista(e))
    return p
#+end_src


*** Ejemplo de funcionamiento

Usaremos la misma lista =ejercicio= que usamos en el capítulo anterior

#+NAME: Ejemplo de ProblemaTipoProfe
#+BEGIN_SRC jupyter-python :results raw
for i in ProblemaTipoProfe( ejercicio ):
    print(i)
#+END_SRC

#+RESULTS: Ejemplo de ProblemaTipoProfe
: ('1', 'Considere A y que A implica C. Conteste: ', [('¿Se da C?', True, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se da D?', False, 1, ''), ('¿Se da E?', "rechazada por v('D')", 0), ('¿Se dan A y C?', True, 1, ''), ('¿Se dan C y D?', False, 1, '')])
: ('2', 'Considere A y que B equivale a D. Conteste: ', [('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se da D?', False, 1, ''), ('¿Se da E?', "rechazada por v('D')", 0), ('¿Se dan A y C?', False, 1, ''), ('¿Se dan C y D?', False, 1, '')])
: ('3', 'Considere B y que A implica C. Conteste: ', [('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se da D?', False, 1, ''), ('¿Se da E?', "rechazada por v('D')", 0), ('¿Se dan A y C?', False, 1, ''), ('¿Se dan C y D?', False, 1, '')])
: ('4', 'Considere B y que B equivale a D. Conteste: ', [('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A'), ('¿Se da D?', True, 1, ''), ('¿Se da E?', False, 1, ''), ('¿Se dan A y C?', False, 1, ''), ('¿Se dan C y D?', False, 1, '')])

Como la vez anterior la representación en una tupla usando =print= se ha extendido más allá de los márgenes de este documento. Para evitar este problema y que el lector vea mejor el funcionamiento de =ProblemaTipoProfe=, vamos usar el mismo truco que en el capítulo anterior: Debajo de cada variante del enunciado completo, mostraremos todas las cuestiones de manera individual, cada una en una línea separada, junto con el cálculo de su veracidad o la indicación de si serán descartadas al emplear la clase =ProblemaTipo=. Si la cuestión incluye el atributo =self.x= con una explicación, también se muestra la explicación (si no, aparece una cadena vacía =''=).


#+BEGIN_SRC jupyter-python
for i in ProblemaTipoProfe( ejercicio ):
    # Desempaquetamos la tupla en variables
    id_pregunta, EnunciadoCompleto, lista_Cuestiones = i

    # Imprimimos los primeros datos
    print(f"ID: {id_pregunta}")
    print(f"Enunciado completo: {EnunciadoCompleto}")

    # Imprimimos la lista de c uestiones, cada cuestión en una línea
    print(*lista_Cuestiones, sep='\n')
    print('\n')
#+END_SRC

#+RESULTS:
#+begin_example
ID: 1
Enunciado completo: Considere A y que A implica C. Conteste: 
('¿Se da C?', True, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se da D?', False, 1, '')
('¿Se da E?', "rechazada por v('D')", 0)
('¿Se dan A y C?', True, 1, '')
('¿Se dan C y D?', False, 1, '')


ID: 2
Enunciado completo: Considere A y que B equivale a D. Conteste: 
('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se da D?', False, 1, '')
('¿Se da E?', "rechazada por v('D')", 0)
('¿Se dan A y C?', False, 1, '')
('¿Se dan C y D?', False, 1, '')


ID: 3
Enunciado completo: Considere B y que A implica C. Conteste: 
('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se da D?', False, 1, '')
('¿Se da E?', "rechazada por v('D')", 0)
('¿Se dan A y C?', False, 1, '')
('¿Se dan C y D?', False, 1, '')


ID: 4
Enunciado completo: Considere B y que B equivale a D. Conteste: 
('¿Se da C?', False, 1, 'Solo sabemos que C es cierto y si A implica C y además sabemos que ocurre A')
('¿Se da D?', True, 1, '')
('¿Se da E?', False, 1, '')
('¿Se dan A y C?', False, 1, '')
('¿Se dan C y D?', False, 1, '')
#+end_example

Vemos que son cuatro enunciados en total, y para cada uno de ellos vemos lo qué pasa con cada una de las cinco cuestiones posibles: si son verdaderas, si son falsas o si serán descartadas (y el motivo).
Ahora es mucho más fácil mejorar y depurar el =ejercicio= que estamos diseñando para nuestros exámenes de opción múltiple.



** Clase =ProblemaVF=

A diferencia de las clases anteriores, que exploran de forma sistemática y secuencial todas las combinaciones posibles de un espacio combinatorio, la clase =ProblemaVF= está diseñada para generar ejercicios basados en un **banco de cuestiones aleatorizado**. 

Su objetivo primordial es construir variantes de exámenes del tipo =Verdadero/Falso=, donde el enunciado permanece fijo y cada variante ofrece un subconjunto único y desordenado de preguntas seleccionadas al azar a partir de un repertorio común.

*** Implementación

El núcleo de esta clase radica en el uso de la función =sample= del módulo =random= de Python, lo que permite extraer muestras sin repetición del banco de preguntas en cada iteración. 

Una particularidad fundamental de este diseño es que el método =__next__= es que no sigue un barrido secuencial de todas las combinaciones posibles. Aquí el iterador generará una variante al azar cada vez que se invoque el método =next()= (obviamente, dado que el banco de cuestiones es finito, aparecerán variantes repetidas de cuando en cuando).

#+NAME: Definición de la clase ProblemaVF
#+begin_src python :noweb yes
from random import sample
class ProblemaVF():
    def __init__(self, enunciado, cuestiones, NumPreguntas):
        self.e = enunciado
        self.c = cuestiones
        self.NumPreguntas = NumPreguntas

    def __iter__(self):
        self.contador = 0
        return self

    def __next__(self):
        cuestiones = sample(self.c, self.NumPreguntas)
        self.contador += 1
        return (str(self.contador), self.e, cuestiones)
#+end_src

**** Métodos de la clase =ProblemaVF=

- *=__init__(self, enunciado, cuestiones, NumPreguntas)=*: Inicializa el generador almacenando el texto base del problema (=enunciado=), la lista completa de tuplas con las preguntas y sus valores de verdad (=cuestiones=), y la cantidad exacta de ítems que se deben extraer para cada ejercicio (=NumPreguntas=).
- *=__iter__(self)=*: Prepara el objeto para ser iterado, inicializando un =self.contador= interno a cero que servirá para identificar unívocamente el ID de cada variante generada.
- *=__next__(self)=*: Constituye el motor de la clase. En cada invocación ejecuta tres pasos:
  1. Utiliza =sample(self.c, self.NumPreguntas)= para obtener una lista con el número de preguntas solicitado, garantizando que en una misma variante no se repita ninguna cuestión.
  2. Incrementa el contador de variantes.
  3. Devuelve una tupla con el identificador en formato de cadena, el enunciado estático y la lista aleatoria de preguntas seleccionadas con sus respectivos estados lógicos (=True/False=).

*Nota de diseño:* Dado que no existe una condición de parada intrínseca (como un extremo de lista), el bucle que consuma este iterador debe limitarse explícitamente desde el exterior (por ejemplo, mediante un bucle =for= con un rango acotado o controlando el número de peticiones).

*** Ejemplo de funcionamiento

A continuación se ilustra el comportamiento de la clase utilizando un banco de diez enunciados cotidianos relacionados con la vida académica.

#+BEGIN_SRC jupyter-python
banco = [
  ("Todo alumno que va a clase aprueba",   False),
  ("Todo alumno que suspende va a clase",  False),
  ("Todo alumno que sabe aprueba",         True ),
  ("Todo alumno que NO sabe suspende",     False ),
  ("Algunos alumnos aprueban copiando",    True ),
  ("Copiar es intolerable",                True ),
  ("Si aprueban todos es estupendo",       True ),
  ("Si aprueban todos eres buen profesor", False),
  ("Si suspenden todos eres mal profesor", False),
  ("Si suspenden todos es frustrante",     True),]
#+END_SRC

#+RESULTS:


**** Generación de cuatro variantes cortas
En este primer ensayo se configuran cuatro ejercicios, solicitando únicamente dos preguntas tipo verdadero/falso para cada uno.

#+NAME: Ejemplo de ProblemaVF
#+BEGIN_SRC jupyter-python
enunciado = "Marque las verdaderas:"

p  = ProblemaVF (enunciado, banco, 2)      # Dos preguntas del banco por variante
p0 = iter(p)

for i in range(4):                         # Generamos cuatro variantes y paramos
    print(next(p0))
#+END_SRC

#+RESULTS: Ejemplo de ProblemaVF
: ('1', 'Marque las verdaderas:', [('Si suspenden todos es frustrante', True), ('Si aprueban todos es estupendo', True)])
: ('2', 'Marque las verdaderas:', [('Copiar es intolerable', True), ('Todo alumno que suspende va a clase', False)])
: ('3', 'Marque las verdaderas:', [('Todo alumno que suspende va a clase', False), ('Si suspenden todos eres mal profesor', False)])
: ('4', 'Marque las verdaderas:', [('Todo alumno que suspende va a clase', False), ('Todo alumno que sabe aprueba', True)])

**** Generación de cinco variantes con presentación formateada
Como la representación en una sola tupla puede dificultar la lectura a medida que el número de ítems crece, vamos a desempaquetar los componentes devueltos por el iterador para volcar los datos de manera estructurada para que se vea mejor el resultado, pues vamos a mostrar cada cuestión en una línea independiente. 

Dado que ahora lo vamos a ver mejor, aumentamos la complejidad solicitando tres preguntas por variante para un total de cinco ejercicios:

#+BEGIN_SRC jupyter-python :results raw
p  = ProblemaVF (enunciado, banco, 3)      # Tres preguntas por variante
p0 = iter(p)

for i in range(5):
    # Desempaquetamos la tupla en variables
    id_pregunta, EnunciadoCompleto, lista_Cuestiones = next(p0)

    # Imprimimos los primeros datos
    f"ID: {id_pregunta}"
    print(f"Enunciado completo: {EnunciadoCompleto}")

    # Imprimimos la lista de cuestiones, cada cuestión en una línea
    print(*lista_Cuestiones, sep='\n')
    print('\n')
#+END_SRC

#+RESULTS:
#+begin_example
Enunciado completo: Marque las verdaderas:
('Copiar es intolerable', True)
('Si suspenden todos eres mal profesor', False)
('Si suspenden todos es frustrante', True)


Enunciado completo: Marque las verdaderas:
('Todo alumno que suspende va a clase', False)
('Si aprueban todos es estupendo', True)
('Si aprueban todos eres buen profesor', False)


Enunciado completo: Marque las verdaderas:
('Si suspenden todos eres mal profesor', False)
('Copiar es intolerable', True)
('Si aprueban todos es estupendo', True)


Enunciado completo: Marque las verdaderas:
('Si suspenden todos es frustrante', True)
('Todo alumno que suspende va a clase', False)
('Todo alumno que va a clase aprueba', False)


Enunciado completo: Marque las verdaderas:
('Todo alumno que NO sabe suspende', False)
('Todo alumno que suspende va a clase', False)
('Todo alumno que sabe aprueba', True)
#+end_example

Como se puede apreciar en el resultado impreso, cada uno de los cinco bloques representa un ejercicio completamente autónomo con un identificador secuencial, conservando el enunciado general invariantemente e integrando un muestreo dinámico y heterogéneo extraído directamente de la lista de afirmaciones almacenada con el nombre de =banco=.



** ¿Y ahora qué?

*** ¿Qué tenemos?

- Contamos con un módulo de cálculo proposicional que determina la veracidad o falsedad de cada enunciado, basada en los supuestos de cada caso particular.
- Poseemos una metodología para programar ejercicios utilizando listas de sublistas que incluyen textos, supuestos y cuestiones.
- Tenemos la capacidad de desempaquetar dichas listas mediante =ProblemaTipo=, lo que nos permite generar múltiples ejercicios, con la tranquilidad de que el módulo de cálculo proposicional se encarga de identificar qué opciones son verdaderas y cuáles son falsas, de acuerdo con la composición de los supuestos de cada enunciado.

Con esto, hemos desarrollado un procedimiento para generar una amplia variedad de ejercicios de opción múltiple.

*** ¿Qué nos falta?

Falta dar formato a lo que hemos desarrollado para ser usado con los estudiantes. El módulo =CalcProp-export= nos permitirá crear bancos de preguntas en formato \LaTeX{}, que podrán ser utilizados con [[https://www.auto-multiple-choice.net/][Auto Multiple Choice (AMC)]], así como también generar bancos en formato =xml= para su empleo en el entorno Moodle mediante el paquete de \LaTeX{} [[https://ctan.org/pkg/moodle][moodle]], específicamente para cuestiones de [[https://docs.moodle.org/502/en/Question_types][opción múltiple]].


* COMMENT otros

#+BEGIN_SRC jupyter-python :results raw
pregunta = [
          "Considere ",
          [Supuesto("A ", v("A")), Supuesto("B ", v("B")), ],
          [Supuesto("y que A implica C. ",    v("A") >> v("C")), Supuesto("y que B equivale a D. ", v("B") ** v("D")), ],
          "Conteste: ",
          [Cuestion("¿Se da C?", v("C")), Cuestion("¿Se da D?", v("D")), Cuestion("¿Se da E?", v("E"), v("D")), Cuestion("¿Se dan A y C?", v("A") & v("C")), Cuestion("¿Se dan C y D?", v("C") & v("D")) ],
      ]

for c in pregunta:
    print(c)
#+END_SRC

#+RESULTS:
: Considere 
: [<calcprop_quiz.Supuesto object at 0x7f521c546850>, <calcprop_quiz.Supuesto object at 0x7f521c545910>]
: [<calcprop_quiz.Supuesto object at 0x7f521c5463d0>, <calcprop_quiz.Supuesto object at 0x7f521c546310>]
: Conteste: 
: [<calcprop_quiz.Cuestion object at 0x7f521c5457d0>, <calcprop_quiz.Cuestion object at 0x7f521c544d50>, <calcprop_quiz.Cuestion object at 0x7f521c545a90>, <calcprop_quiz.Cuestion object at 0x7f521c546ad0>, <calcprop_quiz.Cuestion object at 0x7f521c546490>]

#+BEGIN_SRC jupyter-python
for c in CuestionesJuntas(pregunta):
    print(c)
#+END_SRC

#+RESULTS:
: Considere 
: [<calcprop_quiz.Supuesto object at 0x7f521c546850>, <calcprop_quiz.Supuesto object at 0x7f521c545910>]
: [<calcprop_quiz.Supuesto object at 0x7f521c5463d0>, <calcprop_quiz.Supuesto object at 0x7f521c546310>]
: Conteste: 
: <calcprop_quiz.Cuestion object at 0x7f521c5457d0>
: <calcprop_quiz.Cuestion object at 0x7f521c544d50>
: <calcprop_quiz.Cuestion object at 0x7f521c545a90>
: <calcprop_quiz.Cuestion object at 0x7f521c546ad0>
: <calcprop_quiz.Cuestion object at 0x7f521c546490>


** Clase =ProblemaVF=

Para crear ejercicios con bancos de cuestiones del tipo =Verdadero/Falso=.

#+NAME: Definición de la clase ProblemaVF
#+begin_src python :noweb yes
from random import sample
class ProblemaVF():
    def __init__(self, enunciado, cuestiones, NumPreguntas):
        self.e = enunciado
        self.c = cuestiones
        self.NumPreguntas = NumPreguntas

    def __iter__(self):
        self.contador = 0
        return self

    def __next__(self):
        cuestiones = sample(self.c, self.NumPreguntas)
        self.contador  += 1
        return (str(self.contador), self.e, cuestiones)

#+end_src

*** Ejemplo de funcionamiento

Cuatro ejercicios con dos preguntas tipo verdadero/falso cada uno.
#+NAME: Ejemplo de ProblemaVF
#+BEGIN_SRC jupyter-python
enunciado = "Marque las verdaderas:"

banco = [
  ("Todo alumno que va a clase aprueba",   False),
  ("Todo alumno que suspende va a clase",  False),
  ("Todo alumno que sabe aprueba",         True ),
  ("Todo alumno que NO sabe suspende",     False ),
  ("Algunos alumnos aprueban copiando",    True ),
  ("Copiar es intolerable",                True ),
  ("Si aprueban todos es estupendo",       True ),
  ("Si aprueban todos eres buen profesor", False),
  ("Si suspenden todos eres mal profesor", False),
  ("Si suspenden todos es frustrante",     True),]

p  = ProblemaVF (enunciado, banco, 2)      # tres preguntas por variante
p0 = iter(p)

for i in range(4):                         # cuatro variantes
    print(next(p0))
#+END_SRC

#+RESULTS: Ejemplo de ProblemaVF
: ('1', 'Marque las verdaderas:', [('Todo alumno que sabe aprueba', True), ('Si suspenden todos eres mal profesor', False)])
: ('2', 'Marque las verdaderas:', [('Si suspenden todos eres mal profesor', False), ('Todo alumno que suspende va a clase', False)])
: ('3', 'Marque las verdaderas:', [('Todo alumno que suspende va a clase', False), ('Si aprueban todos eres buen profesor', False)])
: ('4', 'Marque las verdaderas:', [('Si suspenden todos eres mal profesor', False), ('Si aprueban todos es estupendo', True)])


Cinco ejercicios con tres preguntas tipo verdadero/falso cada uno.

#+BEGIN_SRC jupyter-python
p  = ProblemaVF (enunciado, banco, 3)      # Tres preguntas por variante
p0 = iter(p)

for i in range(5):
    # Desempaquetamos la tupla en variables
    id_pregunta, EnunciadoCompleto, lista_Cuestiones = next(p0)

    # Imprimimos los primeros datos
    print(f"ID: {id_pregunta}")
    print(f"Enunciado completo: {EnunciadoCompleto}")

    # Imprimimos la lista de c uestiones, cada cuestión en una línea
    print(*lista_Cuestiones, sep='\n')
    print('\n')
#+END_SRC

#+RESULTS:
#+begin_example
ID: 1
Enunciado completo: Marque las verdaderas:
('Algunos alumnos aprueban copiando', True)
('Todo alumno que suspende va a clase', False)
('Si aprueban todos es estupendo', True)


ID: 2
Enunciado completo: Marque las verdaderas:
('Si aprueban todos eres buen profesor', False)
('Todo alumno que sabe aprueba', True)
('Todo alumno que NO sabe suspende', False)


ID: 3
Enunciado completo: Marque las verdaderas:
('Todo alumno que va a clase aprueba', False)
('Si aprueban todos es estupendo', True)
('Todo alumno que suspende va a clase', False)


ID: 4
Enunciado completo: Marque las verdaderas:
('Si suspenden todos es frustrante', True)
('Si aprueban todos eres buen profesor', False)
('Todo alumno que suspende va a clase', False)


ID: 5
Enunciado completo: Marque las verdaderas:
('Si suspenden todos eres mal profesor', False)
('Todo alumno que suspende va a clase', False)
('Algunos alumnos aprueban copiando', True)
#+end_example

